services:
  api:
    container_name: "snippet-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
      - redis

  db:
    container_name: "snippet-db"
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snippet-db
    volumes:
      - snippet-db:/var/lib/postgresql/data

  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  snippet-db: