services:
  api:
    container_name: "snippet-api"
    build:
      context: .
    ports:
      - "8050:8080" # Expose Spring Boot app on 8050 externally
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: snippet-db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    container_name: "snippet-db"
    image: postgres:17
    ports:
      - 5450:5432 # Host:Container port mapping
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - snippet-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

volumes:
  snippet-db: