services:
  api:
    container_name: "snippet-api"
    build:
      context: .
    ports:
      - "8082:8080"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "snippet_db"
      DB_HOST: "db"
      DB_PORT: 5432
    networks:
      - printscript_network
    depends_on:
      - db

  db:
    container_name: "snippet_db"
    image: postgres:alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "snippet_db"
    volumes:
      - snippet_db:/var/lib/postgresql/data
    networks:
      - snippet_network

volumes:
  snippet_db:

networks:
  snippet_network:
    external: true