auth0:
  audience: "https://snippet-searcher/"

spring:
  application:
    name: "snippet-service"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-z8z6elh804gqgf0d.us.auth0.com/"