auth0:
  audience: ${AUTH0_AUDIENCE}
spring:
  application:
    name: resource-service-with-auth-example
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_SERVER_URI}
          client-id: ${AUTH0_CLIENT_ID}
          client-secret: ${AUTH0_CLIENT_SECRET}
